name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          cache: 'gradle'
          java-version: |
            17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Cache Konan
        id: cache-kotlin-konan
        uses: actions/cache@v5
        with:
          path: |
            ~/.konan/**/*
          key: kotlin-konan

      - name: Build project
        run: ./gradlew compileAllTargets --build-cache --parallel --no-daemon
